############################
## CHANGE THESE
############################

baseURL: "https://Eisbrenner.github.io/home"
title: "Ezra Eisbrenner"

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
