############################
## CHANGE THESE
############################

baseURL: "https://eisbrenner.github.io/"
title: "Ezra Eisbrenner"

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
