############################
## Author
############################

author:
  name: Ezra Eisbrenner
  image: author.png
  greeting: "Data Scientist 🫩"
  icon: ":wave:"

############################
## Links
############################

links:
  - linkedin: https://linkedin.com/in/ezra-eisbrenner
  - github: https://github.com/Eisbrenner
  - mastodon: https://vis.social/@ezra_eisbrenner
  - orcid: https://orcid.org/0000-0002-4042-6087
  # - link:
  # - website:
  # - x-twitter:
  # - mastodon:
  # - instagram:
  # - reddit:
  # - telegram:
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  # - email:
  # - discord:
  # - slack:
  # - stack-overflow:
  # - twitch:
  # - patreon:
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  # - youtube:
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - bluesky:
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  # - spotify:
  # - pinterest:
  # - strava:
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: eisbrenner.github.io
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
